// Code generated by gowrap. DO NOT EDIT.
// template: https://raw.githubusercontent.com/hexdigest/gowrap/6c8f05695fec23df85903a8da0af66ac414e2a63/templates/opentelemetry
// gowrap: http://github.com/hexdigest/gowrap

package traced

import (
	"context"

	"github.com/dell/goobjectscale/pkg/client/api"
	"github.com/dell/goobjectscale/pkg/client/model"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

// FederatedObjectStoresInterfaceWithTracing implements api.FederatedObjectStoresInterface interface instrumented with opentracing spans
type FederatedObjectStoresInterfaceWithTracing struct {
	api.FederatedObjectStoresInterface
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewFederatedObjectStoresInterfaceWithTracing returns FederatedObjectStoresInterfaceWithTracing
func NewFederatedObjectStoresInterfaceWithTracing(base api.FederatedObjectStoresInterface, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) FederatedObjectStoresInterfaceWithTracing {
	d := FederatedObjectStoresInterfaceWithTracing{
		FederatedObjectStoresInterface: base,
		_instance:                      instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// List implements api.FederatedObjectStoresInterface
func (_d FederatedObjectStoresInterfaceWithTracing) List(ctx context.Context, params map[string]string) (fp1 *model.FederatedObjectStoreList, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "api.FederatedObjectStoresInterface.List")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":    ctx,
				"params": params}, map[string]interface{}{
				"fp1": fp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.FederatedObjectStoresInterface.List(ctx, params)
}
