name: Bug report
description: Create a report to help us improve.
title: "[BUG]: "
labels: ["type/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to create a goobjectscale bug report. To better help us investigate this bug, please provide the information below.
  - type: dropdown
    id: version
    attributes:
      label: What version of ObjectScale are you seeing the problem on?
      multiple: true
      options: # NOTE: maintain the list of supported versions.
        - v1.0.x
        - v1.2.x
        - other
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: Logs
      description: Copy/paste any relevant log output here or Upload log files by dragging and dropping the files into the text area. Please be sure to remove all sensitive data such as IP addresses, host names, credentials, etc.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps can taken to reproduce this bug?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
