// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dell/goobjectscale/pkg/client/model"
	mock "github.com/stretchr/testify/mock"
)

// BucketServiceInterface is an autogenerated mock type for the BucketServiceInterface type
type BucketServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, createParam
func (_m *BucketServiceInterface) Create(ctx context.Context, createParam *model.ObjectBucketParam) (*model.Bucket, error) {
	ret := _m.Called(ctx, createParam)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Bucket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ObjectBucketParam) (*model.Bucket, error)); ok {
		return rf(ctx, createParam)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.ObjectBucketParam) *model.Bucket); ok {
		r0 = rf(ctx, createParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bucket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.ObjectBucketParam) error); ok {
		r1 = rf(ctx, createParam)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, bucketName, param
func (_m *BucketServiceInterface) Delete(ctx context.Context, bucketName string, param map[string]string) error {
	ret := _m.Called(ctx, bucketName, param)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = rf(ctx, bucketName, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePolicy provides a mock function with given fields: ctx, bucketName, param
func (_m *BucketServiceInterface) DeletePolicy(ctx context.Context, bucketName string, param map[string]string) error {
	ret := _m.Called(ctx, bucketName, param)

	if len(ret) == 0 {
		panic("no return value specified for DeletePolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = rf(ctx, bucketName, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, bucketName, param
func (_m *BucketServiceInterface) Get(ctx context.Context, bucketName string, param map[string]string) (*model.Bucket, error) {
	ret := _m.Called(ctx, bucketName, param)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Bucket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) (*model.Bucket, error)); ok {
		return rf(ctx, bucketName, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) *model.Bucket); ok {
		r0 = rf(ctx, bucketName, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bucket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, bucketName, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPolicy provides a mock function with given fields: ctx, bucketName, param
func (_m *BucketServiceInterface) GetPolicy(ctx context.Context, bucketName string, param map[string]string) (string, error) {
	ret := _m.Called(ctx, bucketName, param)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicy")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) (string, error)); ok {
		return rf(ctx, bucketName, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) string); ok {
		r0 = rf(ctx, bucketName, param)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, bucketName, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, param
func (_m *BucketServiceInterface) List(ctx context.Context, param map[string]string) (*model.BucketList, error) {
	ret := _m.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.BucketList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) (*model.BucketList, error)); ok {
		return rf(ctx, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) *model.BucketList); ok {
		r0 = rf(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BucketList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePolicy provides a mock function with given fields: ctx, bucketName, policy, param
func (_m *BucketServiceInterface) UpdatePolicy(ctx context.Context, bucketName string, policy string, param map[string]string) error {
	ret := _m.Called(ctx, bucketName, policy, param)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) error); ok {
		r0 = rf(ctx, bucketName, policy, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBucketServiceInterface creates a new instance of BucketServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBucketServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BucketServiceInterface {
	mock := &BucketServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
