// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "github.com/dell/goobjectscale/pkg/client/model"
	mock "github.com/stretchr/testify/mock"
)

// BucketsInterface is an autogenerated mock type for the BucketsInterface type
type BucketsInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: createParam
func (_m *BucketsInterface) Create(createParam model.Bucket) (*model.Bucket, error) {
	ret := _m.Called(createParam)

	var r0 *model.Bucket
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Bucket) (*model.Bucket, error)); ok {
		return rf(createParam)
	}
	if rf, ok := ret.Get(0).(func(model.Bucket) *model.Bucket); ok {
		r0 = rf(createParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bucket)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Bucket) error); ok {
		r1 = rf(createParam)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: name, namespace, emptyBucket
func (_m *BucketsInterface) Delete(name string, namespace string, emptyBucket bool) error {
	ret := _m.Called(name, namespace, emptyBucket)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = rf(name, namespace, emptyBucket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePolicy provides a mock function with given fields: bucketName, param
func (_m *BucketsInterface) DeletePolicy(bucketName string, param map[string]string) error {
	ret := _m.Called(bucketName, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]string) error); ok {
		r0 = rf(bucketName, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteQuota provides a mock function with given fields: bucketName, namespace
func (_m *BucketsInterface) DeleteQuota(bucketName string, namespace string) error {
	ret := _m.Called(bucketName, namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(bucketName, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: name, params
func (_m *BucketsInterface) Get(name string, params map[string]string) (*model.Bucket, error) {
	ret := _m.Called(name, params)

	var r0 *model.Bucket
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]string) (*model.Bucket, error)); ok {
		return rf(name, params)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]string) *model.Bucket); ok {
		r0 = rf(name, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bucket)
		}
	}

	if rf, ok := ret.Get(1).(func(string, map[string]string) error); ok {
		r1 = rf(name, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPolicy provides a mock function with given fields: bucketName, param
func (_m *BucketsInterface) GetPolicy(bucketName string, param map[string]string) (string, error) {
	ret := _m.Called(bucketName, param)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]string) (string, error)); ok {
		return rf(bucketName, param)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]string) string); ok {
		r0 = rf(bucketName, param)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, map[string]string) error); ok {
		r1 = rf(bucketName, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuota provides a mock function with given fields: bucketName, namespace
func (_m *BucketsInterface) GetQuota(bucketName string, namespace string) (*model.BucketQuotaInfo, error) {
	ret := _m.Called(bucketName, namespace)

	var r0 *model.BucketQuotaInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.BucketQuotaInfo, error)); ok {
		return rf(bucketName, namespace)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.BucketQuotaInfo); ok {
		r0 = rf(bucketName, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BucketQuotaInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(bucketName, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: params
func (_m *BucketsInterface) List(params map[string]string) (*model.BucketList, error) {
	ret := _m.Called(params)

	var r0 *model.BucketList
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) (*model.BucketList, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) *model.BucketList); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BucketList)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePolicy provides a mock function with given fields: bucketName, policy, param
func (_m *BucketsInterface) UpdatePolicy(bucketName string, policy string, param map[string]string) error {
	ret := _m.Called(bucketName, policy, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, map[string]string) error); ok {
		r0 = rf(bucketName, policy, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateQuota provides a mock function with given fields: bucketQuota
func (_m *BucketsInterface) UpdateQuota(bucketQuota model.BucketQuotaUpdate) error {
	ret := _m.Called(bucketQuota)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.BucketQuotaUpdate) error); ok {
		r0 = rf(bucketQuota)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBucketsInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewBucketsInterface creates a new instance of BucketsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBucketsInterface(t mockConstructorTestingTNewBucketsInterface) *BucketsInterface {
	mock := &BucketsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
