// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	api "github.com/dell/goobjectscale/pkg/client/api"
	mock "github.com/stretchr/testify/mock"
)

// ClientSet is an autogenerated mock type for the ClientSet type
type ClientSet struct {
	mock.Mock
}

// Buckets provides a mock function with no fields
func (_m *ClientSet) Buckets() api.BucketServiceInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Buckets")
	}

	var r0 api.BucketServiceInterface
	if rf, ok := ret.Get(0).(func() api.BucketServiceInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.BucketServiceInterface)
		}
	}

	return r0
}

// VPools provides a mock function with no fields
func (_m *ClientSet) VPools() api.VPoolServiceInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VPools")
	}

	var r0 api.VPoolServiceInterface
	if rf, ok := ret.Get(0).(func() api.VPoolServiceInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.VPoolServiceInterface)
		}
	}

	return r0
}

// NewClientSet creates a new instance of ClientSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientSet(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientSet {
	mock := &ClientSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
