// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dell/goobjectscale/pkg/client/model"
	mock "github.com/stretchr/testify/mock"
)

// FederatedObjectStoresInterface is an autogenerated mock type for the FederatedObjectStoresInterface type
type FederatedObjectStoresInterface struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, params
func (_m *FederatedObjectStoresInterface) List(ctx context.Context, params map[string]string) (*model.FederatedObjectStoreList, error) {
	ret := _m.Called(ctx, params)

	var r0 *model.FederatedObjectStoreList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) (*model.FederatedObjectStoreList, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) *model.FederatedObjectStoreList); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FederatedObjectStoreList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFederatedObjectStoresInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewFederatedObjectStoresInterface creates a new instance of FederatedObjectStoresInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFederatedObjectStoresInterface(t mockConstructorTestingTNewFederatedObjectStoresInterface) *FederatedObjectStoresInterface {
	mock := &FederatedObjectStoresInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
