// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dell/goobjectscale/pkg/client/model"
	mock "github.com/stretchr/testify/mock"
)

// TenantsInterface is an autogenerated mock type for the TenantsInterface type
type TenantsInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payload
func (_m *TenantsInterface) Create(ctx context.Context, payload model.TenantCreate) (*model.Tenant, error) {
	ret := _m.Called(ctx, payload)

	var r0 *model.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TenantCreate) (*model.Tenant, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TenantCreate) *model.Tenant); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TenantCreate) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, name
func (_m *TenantsInterface) Delete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteQuota provides a mock function with given fields: ctx, name
func (_m *TenantsInterface) DeleteQuota(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, name, params
func (_m *TenantsInterface) Get(ctx context.Context, name string, params map[string]string) (*model.Tenant, error) {
	ret := _m.Called(ctx, name, params)

	var r0 *model.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) (*model.Tenant, error)); ok {
		return rf(ctx, name, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) *model.Tenant); ok {
		r0 = rf(ctx, name, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, name, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuota provides a mock function with given fields: ctx, name, params
func (_m *TenantsInterface) GetQuota(ctx context.Context, name string, params map[string]string) (*model.TenantQuota, error) {
	ret := _m.Called(ctx, name, params)

	var r0 *model.TenantQuota
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) (*model.TenantQuota, error)); ok {
		return rf(ctx, name, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) *model.TenantQuota); ok {
		r0 = rf(ctx, name, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantQuota)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, name, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, params
func (_m *TenantsInterface) List(ctx context.Context, params map[string]string) (*model.TenantList, error) {
	ret := _m.Called(ctx, params)

	var r0 *model.TenantList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) (*model.TenantList, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) *model.TenantList); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetQuota provides a mock function with given fields: ctx, name, payload
func (_m *TenantsInterface) SetQuota(ctx context.Context, name string, payload model.TenantQuotaSet) error {
	ret := _m.Called(ctx, name, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.TenantQuotaSet) error); ok {
		r0 = rf(ctx, name, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, payload, name
func (_m *TenantsInterface) Update(ctx context.Context, payload model.TenantUpdate, name string) error {
	ret := _m.Called(ctx, payload, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TenantUpdate, string) error); ok {
		r0 = rf(ctx, payload, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTenantsInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewTenantsInterface creates a new instance of TenantsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTenantsInterface(t mockConstructorTestingTNewTenantsInterface) *TenantsInterface {
	mock := &TenantsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
