// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dell/goobjectscale/pkg/client/model"
	mock "github.com/stretchr/testify/mock"
)

// VPoolServiceInterface is an autogenerated mock type for the VPoolServiceInterface type
type VPoolServiceInterface struct {
	mock.Mock
}

// List provides a mock function with given fields: _a0
func (_m *VPoolServiceInterface) List(_a0 context.Context) ([]model.DataServiceVPool, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.DataServiceVPool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.DataServiceVPool, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.DataServiceVPool); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DataServiceVPool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVPoolServiceInterface creates a new instance of VPoolServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVPoolServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *VPoolServiceInterface {
	mock := &VPoolServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
